services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    ports:
      - "8080:80"

    environment:
      FTLCONF_dns_listeningMode: all
      DNSMASQ_USER: pihole
      PIHOLE_UID: 1000
      PIHOLE_GID: 1000
      FTLCONF_webserver_api_password: admin

    volumes:
      - ./pihole/pihole:/etc/pihole
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d

    restart: unless-stopped