services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    ports:
      - 9080:80
    restart: always
